
export const GET_ALL_REST_API= 'GET_ALL_REST_API';
export const GET_ALL_REST_API_SUCCESS = 'GET_ALL_REST_API_SUCCESS';
export const GET_ALL_REST_API_ERROR = 'GET_ALL_REST_API_ERROR';
export const RELOAD_DATA_REST_API= 'RELOAD_DATA_REST_API';


export const SHOW_CREATE_REST_API_FORM = "SHOW_CREATE_REST_API_FORM";
export const CREATE_REST_API = "CREATE_REST_API";
export const CREATE_REST_API_SUCCESS = "CREATE_REST_API_SUCCESS";
export const CREATE_REST_API_ERROR = "CREATE_REST_API_ERROR";

export const SHOW_UPDATE_REST_API_FORM = "SHOW_UPDATE_REST_API_FORM";
export const UPDATE_REST_API = "UPDATE_REST_API";
export const UPDATE_REST_API_SUCCESS = "UPDATE_REST_API_SUCCESS";
export const UPDATE_REST_API_ERROR = "UPDATE_REST_API_ERROR";

export const CLICK_DELETE_REST_API_BUTTON = "CLICK_DELETE_REST_API_BUTTON";
export const SHOW_DELETE_REST_API_CONFIRM = "SHOW_DELETE_REST_API_CONFIRM";
export const DELETE_REST_API = "DELETE_REST_API";
export const DELETE_REST_API_SUCCESS = "DELETE_REST_API_SUCCESS";
export const DELETE_REST_API_ERROR = "DELETE_REST_API_ERROR";


export const GET_GROUP_REST_API= 'GET_GROUP_REST_API';
export const GET_GROUP_REST_API_SUCCESS = 'GET_GROUP_REST_API_SUCCESS';
export const GET_GROUP_REST_API_ERROR = 'GET_GROUP_REST_API_ERROR';
