export const LIST_TIMESHEET_BY_MONTH = 'LIST_TIMESHEET_BY_MONTH';
export const LIST_TIMESHEET_BY_MONTH_ERROR = 'LIST_TIMESHEET_BY_MONTH_ERROR';
export const LIST_TIMESHEET_BY_MONTH_SUCCESS = 'LIST_TIMESHEET_BY_MONTH_SUCCESS';

export const LIST_ATTENDANCE_BY_MONTH = 'LIST_ATTENDANCE_BY_MONTH';
export const LIST_ATTENDANCE_BY_MONTH_ERROR = 'LIST_ATTENDANCE_BY_MONTH_ERROR';
export const LIST_ATTENDANCE_BY_MONTH_SUCCESS = 'LIST_ATTENDANCE_BY_MONTH_SUCCESS';

export const GET_STATISTIC_BY_MONTH = 'GET_STATISTIC_BY_MONTH';
export const GET_STATISTIC_BY_MONTH_ERROR = 'GET_STATISTIC_BY_MONTH_ERROR';
export const GET_STATISTIC_BY_MONTH_SUCCESS = 'GET_STATISTIC_BY_MONTH_SUCCESS';
