
export const GET_ALL_DATA_SERVICE= 'GET_ALL_DATA_SERVICE';
export const GET_ALL_DATA_SERVICE_SUCCESS = 'GET_ALL_DATA_SERVICE_SUCCESS';
export const GET_ALL_DATA_SERVICE_ERROR = 'GET_ALL_DATA_SERVICE_ERROR';
export const RELOAD_DATA_DATA_SERVICE= 'RELOAD_DATA_DATA_SERVICE';


export const SHOW_CREATE_DATA_SERVICE_FORM = "SHOW_CREATE_DATA_SERVICE_FORM";
export const CREATE_DATA_SERVICE = "CREATE_DATA_SERVICE";
export const CREATE_DATA_SERVICE_SUCCESS = "CREATE_DATA_SERVICE_SUCCESS";
export const CREATE_DATA_SERVICE_ERROR = "CREATE_DATA_SERVICE_ERROR";

export const SHOW_UPDATE_DATA_SERVICE_FORM = "SHOW_UPDATE_DATA_SERVICE_FORM";
export const UPDATE_DATA_SERVICE = "UPDATE_DATA_SERVICE";
export const UPDATE_DATA_SERVICE_SUCCESS = "UPDATE_DATA_SERVICE_SUCCESS";
export const UPDATE_DATA_SERVICE_ERROR = "UPDATE_DATA_SERVICE_ERROR";

export const CLICK_DELETE_DATA_SERVICE_BUTTON = "CLICK_DELETE_DATA_SERVICE_BUTTON";
export const SHOW_DELETE_DATA_SERVICE_CONFIRM = "SHOW_DELETE_DATA_SERVICE_CONFIRM";
export const DELETE_DATA_SERVICE = "DELETE_DATA_SERVICE";
export const DELETE_DATA_SERVICE_SUCCESS = "DELETE_DATA_SERVICE_SUCCESS";
export const DELETE_DATA_SERVICE_ERROR = "DELETE_DATA_SERVICE_ERROR";

export const GET_SINGLE_DATA_SERVICE= 'GET_SINGLE_DATA_SERVICE';
export const GET_SINGLE_DATA_SERVICE_SUCCESS = 'GET_SINGLE_DATA_SERVICE_SUCCESS';
export const GET_SINGLE_DATA_SERVICE_ERROR = 'GET_SINGLE_DATA_SERVICE_ERROR';
