
export const GET_ALL_GROUP_REST_API= 'GET_ALL_GROUP_REST_API';
export const GET_ALL_GROUP_REST_API_SUCCESS = 'GET_ALL_GROUP_REST_API_SUCCESS';
export const GET_ALL_GROUP_REST_API_ERROR = 'GET_ALL_GROUP_REST_API_ERROR';
export const RELOAD_DATA_GROUP_REST_API= 'RELOAD_DATA_GROUP_REST_API';


export const SHOW_CREATE_GROUP_REST_API_FORM = "SHOW_CREATE_GROUP_REST_API_FORM";
export const CREATE_GROUP_REST_API = "CREATE_GROUP_REST_API";
export const CREATE_GROUP_REST_API_SUCCESS = "CREATE_GROUP_REST_API_SUCCESS";
export const CREATE_GROUP_REST_API_ERROR = "CREATE_GROUP_REST_API_ERROR";

export const SHOW_UPDATE_GROUP_REST_API_FORM = "SHOW_UPDATE_GROUP_REST_API_FORM";
export const UPDATE_GROUP_REST_API = "UPDATE_GROUP_REST_API";
export const UPDATE_GROUP_REST_API_SUCCESS = "UPDATE_GROUP_REST_API_SUCCESS";
export const UPDATE_GROUP_REST_API_ERROR = "UPDATE_GROUP_REST_API_ERROR";

export const CLICK_DELETE_GROUP_REST_API_BUTTON = "CLICK_DELETE_GROUP_REST_API_BUTTON";
export const SHOW_DELETE_GROUP_REST_API_CONFIRM = "SHOW_DELETE_GROUP_REST_API_CONFIRM";
export const DELETE_GROUP_REST_API = "DELETE_GROUP_REST_API";
export const DELETE_GROUP_REST_API_SUCCESS = "DELETE_GROUP_REST_API_SUCCESS";
export const DELETE_GROUP_REST_API_ERROR = "DELETE_GROUP_REST_API_ERROR";
