
export const GET_ALL_QUERY= 'GET_ALL_QUERY';
export const GET_ALL_QUERY_SUCCESS = 'GET_ALL_QUERY_SUCCESS';
export const GET_ALL_QUERY_ERROR = 'GET_ALL_QUERY_ERROR';
export const RELOAD_DATA_QUERY= 'RELOAD_DATA_QUERY';


export const SHOW_CREATE_QUERY_FORM = "SHOW_CREATE_QUERY_FORM";
export const CREATE_QUERY = "CREATE_QUERY";
export const CREATE_QUERY_SUCCESS = "CREATE_QUERY_SUCCESS";
export const CREATE_QUERY_ERROR = "CREATE_QUERY_ERROR";

export const SHOW_UPDATE_QUERY_FORM = "SHOW_UPDATE_QUERY_FORM";
export const UPDATE_QUERY = "UPDATE_QUERY";
export const UPDATE_QUERY_SUCCESS = "UPDATE_QUERY_SUCCESS";
export const UPDATE_QUERY_ERROR = "UPDATE_QUERY_ERROR";

export const CLICK_DELETE_QUERY_BUTTON = "CLICK_DELETE_QUERY_BUTTON";
export const SHOW_DELETE_QUERY_CONFIRM = "SHOW_DELETE_QUERY_CONFIRM";
export const DELETE_QUERY = "DELETE_QUERY";
export const DELETE_QUERY_SUCCESS = "DELETE_QUERY_SUCCESS";
export const DELETE_QUERY_ERROR = "DELETE_QUERY_ERROR";

export const SHOW_QUERY_DETAIL= 'SHOW_QUERY_DETAIL';
export const GET_QUERY_DETAIL= 'GET_QUERY_DETAIL';
export const GET_QUERY_DETAIL_SUCCESS = 'GET_QUERY_DETAIL_SUCCESS';
export const GET_QUERY_DETAIL_ERROR = 'GET_QUERY_DETAIL_ERROR';
