
export const GET_ALL_DATA_SOURCE= 'GET_ALL_DATA_SOURCE';
export const GET_ALL_DATA_SOURCE_SUCCESS = 'GET_ALL_DATA_SOURCE_SUCCESS';
export const GET_ALL_DATA_SOURCE_ERROR = 'GET_ALL_DATA_SOURCE_ERROR';
export const RELOAD_DATA_DATA_SOURCE= 'RELOAD_DATA_DATA_SOURCE';


export const SHOW_CREATE_DATA_SOURCE_FORM = "SHOW_CREATE_DATA_SOURCE_FORM";
export const CREATE_DATA_SOURCE = "CREATE_DATA_SOURCE";
export const CREATE_DATA_SOURCE_SUCCESS = "CREATE_DATA_SOURCE_SUCCESS";
export const CREATE_DATA_SOURCE_ERROR = "CREATE_DATA_SOURCE_ERROR";

export const SHOW_UPDATE_DATA_SOURCE_FORM = "SHOW_UPDATE_DATA_SOURCE_FORM";
export const UPDATE_DATA_SOURCE = "UPDATE_DATA_SOURCE";
export const UPDATE_DATA_SOURCE_SUCCESS = "UPDATE_DATA_SOURCE_SUCCESS";
export const UPDATE_DATA_SOURCE_ERROR = "UPDATE_DATA_SOURCE_ERROR";

export const CLICK_DELETE_DATA_SOURCE_BUTTON = "CLICK_DELETE_DATA_SOURCE_BUTTON";
export const SHOW_DELETE_DATA_SOURCE_CONFIRM = "SHOW_DELETE_DATA_SOURCE_CONFIRM";
export const DELETE_DATA_SOURCE = "DELETE_DATA_SOURCE";
export const DELETE_DATA_SOURCE_SUCCESS = "DELETE_DATA_SOURCE_SUCCESS";
export const DELETE_DATA_SOURCE_ERROR = "DELETE_DATA_SOURCE_ERROR";

export const GET_SINGLE_DATA_SOURCE= 'GET_SINGLE_DATA_SOURCE';
export const GET_SINGLE_DATA_SOURCE_SUCCESS = 'GET_SINGLE_DATA_SOURCE_SUCCESS';
export const GET_SINGLE_DATA_SOURCE_ERROR = 'GET_SINGLE_DATA_SOURCE_ERROR';
