
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';
export const RELOAD_DATA_USERS = 'RELOAD_DATA_USERS';

export const SHOW_CREATE_USER_FORM = "SHOW_CREATE_USER_FORM";
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const SHOW_UPDATE_USER_FORM = "SHOW_UPDATE_USER_FORM";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CLICK_DELETE_USER_BUTTON = "CLICK_DELETE_USER_BUTTON";
export const SHOW_DELETE_USER_CONFIRM = "SHOW_DELETE_USER_CONFIRM";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
