import {EventEmitter} from 'eventemitter3';

const emitter = new EventEmitter();

const EventTypes = {
  CHOOSE_LAYOUT: 'CHOOSE_LAYOUT',
  CHECKINOUT_CAMERA: 'CHECKINOUT_CAMERA',
  CHOOSE_CAMERA: 'CHOOSE_CAMERA',
  MOVE_CHOOSE_CAMERA: 'MOVE_CHOOSE_CAMERA',
  CHOOSE_CAMERA_AREA: 'CHOOSE_CAMERA_AREA',
  FOCUS_LAYOUT: 'FOCUS_LAYOUT',
  CHOOSE_CHECK_TYPE: 'CHOOSE_CHECK_TYPE',
  NEW_EVENT: 'NEW_EVENT',
  FETCH_NEW_CAMERA: 'FETCH_NEW_CAMERA',
  DELETE_CAMERA_IN_LIST: 'DELETE_CAMERA_IN_LIST',
  RELOAD_LOGS_OVERTIME_REQUEST: 'RELOAD_LOGS_OVERTIME_REQUEST',
  RELOAD_PAGE: "RELOAD_PAGE",
  RELOAD_LOGS_LEAVE_REQUEST: 'RELOAD_LOGS_LEAVE_REQUEST',
  RELOAD_LOGS_FORGET_CHECKIN: 'RELOAD_LOGS_FORGET_CHECKIN',
  RELOAD_LOGS_OUTSIDE_WORKING: 'RELOAD_LOGS_OUTSIDE_WORKING',
  RESET_EMPLOYEE_SELECTOR: 'RESET_EMPLOYEE_SELECTOR',
};

export {emitter, EventTypes};
